
export enum VALIDATION_MESSAGES {
  characters = 'ERROR_VALIDATORS.CHARACTERS',
  required = "ERROR_VALIDATORS.REQUIRED",
  email = "ERROR_VALIDATORS.EMAIL",
  minlength = "ERROR_VALIDATORS.MIN_LENGTH",
  maxlength = "ERROR_VALIDATORS.MAX_LENGTH",
}
